lsyncd:
  container_name: lsyncd
  image: daryljocky/rsync
  privileged: true
  restart: always
  environment:
  - "SERVER_IP=172.17.0.1"
  - "SECTION={{SECTION}}"
  - "SYNC_PASSWORD={{PASSWORD}}"
  volumes:
  - /tmp/test:/data 
