lsyncd:
  container_name: lsyncd
  image: daryljocky/rsync
  privileged: true
  restart: always
  environment:
  - "SERVER_IP={{SERVER_IP}}"
  - "SECTION={{SECTION}}"
  - "SYNC_PASSWORD={{PASSWORD}}"
  volumes:
  - /tmp/test:/data 
  - /data/var/log/lsyncd:/var/log/lsyncd
  - /etc/localtime:/etc/localtime
  entrypoint: /docker-entrypoint-lsyncd.sh
