rsyncd:
  container_name: rsyncd
  image: daryljocky/rsync
  privileged: true
  restart: always
  ports:
  - 873:873
  environment:
  - "SECTION={{SECTION}}"
  - "SYNC_PASSWORD={{PASSWORD}}"
  volumes:
  - /tmp/test2:/data 
  - ./docker-entrypoint-rsyncd.sh:/docker-entrypoint.sh
